const translations = {
    //English
    en : {
        home: {
            title: "Welcome to the VETTER APP",
            description: "The objective of this Erasmus+ KA2 project is to better the quality of internships in VET companies by improving the involvement & participation of the three key actors in the environment of VET training: VET centres, companies & students.",
            about_btn: "About the Project",
            network_btn: "Network & Badge",
            e_learning_btn: "E-learning Course",
            guide_btn: "Methodological Guide",
        },
        about: {
            header: "About the Project",
            title: "VETTER is an Erasmus+ KA2 project that runs from December 2021 to January 2024.",
            description_p1: "The VETTER project aims at improving the evaluation and monitoring process of internships carried out by VET students, as this process sometimes lacks quality and does not take into account several dimensions of the students' life.",
            description_p2: "The VETTER project aims at improving these processes, providing new methodologies and innovative methods that can make the monitoring and evaluation of the internship period of students more transparent and useful for all parties involved. In this way, the VETTER project aims to work along the lines of the Erasmus+ priority of supporting the development of VET programmes which offer a balanced mix of vocational skills and create work-based learning opportunities well aligned to all economic cycles, evolving jobs, working methods and key competences.",
            description_p3: "In order to deliver a high-quality VET training, it is necessary to adapt the programmes to the needs of the labour market, as well as to strengthen the communication and coordination among the agents involved i the process: VET centres, students and companies. This project aims to promote the experience of VET placements, the quality of life at work and synergies between organisations and VET centres for a better management and coordination of work placements.",
        },
        e_learning: {
            header: "E-learning Cource",
            description: "The VETTER e-learning course is a MOOC course with 5 modules on how to improve health and quality of life at work in a holistic way, as well as to provide mechanisms for both companies and vocational training centres to identify concrete needs and implement changes in the development of their practices to ensure their quality and coordinated supervision. This tool is designed so that, before starting the internship, centres and companies complete this course to ensure the right cooperation methodologies and quality of life at work.",
            outcome_title: "How will the user benefit, and what he/she will gain?",
            outcome_description: "After the user finishes the course, he/she will have gained important knowledge and understanding of all aspects of an internship - such as methods and practices to ensure quality internships, resources covering the entire work placement process, how to establish quality guidelines and directives from the beginning to the end of the placement, and of course, practices on how to ensure quality internships altogether.",
            get_course_now: "Get The Course Now",
            beneficiaries_title: "Beneficiaries",
            beneficiary_1: "Internship Tutors",
            beneficiary_2: "Mentors",
            beneficiary_3: "Career Counsellors",
            beneficiary_4: "Vocational Education & Training (VET) Schools",
            beneficiary_5: "Companies",
            beneficiary_6: "Employers involved in work placements and trainees/interns.",
        },
        methodological_guide: {
            header: "Methodological Guide",
            description_p1: "The partnership developed a guide addressed to companies and VET centres with a series of guidelines and recommendations to improve the quality of life at work, health, coordination of internships and their follow-up.",
            description_p2: "This will ensure that they take place in a suitable, supervisory environment that maximises their value.",
            description_p3: "The methodological guide will be mainly oriented to the coordinated implementation of placements by providing basic quality guidelines and could become a relevant tool for mobility projects in the future, allowing both companies and VET centres to manage the internship period in a more organised manner.",
            coming_soon: "Download guide",
        },
        network: {
            header: "Network & Badge",
            description_p1: "As a qualified professional from either a company or vocational education & training (VET) institution, you now have the opportunity to register for our international VETTER Network.",
            description_p2: "The international VETTER Network brings together likeminded individuals and organisations across Europe (i.e., Germany, Italy, Greece, Cyprus) and Turkey - and beyond - committed to the Erasmus+ priority of supporting the development of VET programmes which offer a balanced mix of vocational skills and create work-based learning opportunities well aligned to all economic cycles, evolving jobs, and working methods and key competences.",
            description_p3: "By joining the VETTER Network, you commit to aligning to the Erasmus+ VETTER project values to promote the improved experience of vocational education and training (VET) placements, the quality of life at work, and synergies between organisations and VET centres for a better management and coordination of work placements. As a network member, you pledge to adhere to the project's objectives and use its intellectual products - the free, open-source, European-funded VETTER e-Learning course, mobile app, and digital methodological guidebook.",
            join_form_title: "Join the VETTER Network",
            fullname: "Full Name",
            country: "Country",
            organization: "Organization (optional)",
            email: "Email Address",
            apply_now: "Apply Now",
            email_sent: "Request email sent!",
            email_not_valid: "Not a valid email.",
            required_field: "This field is required.",
            newsletter: "I would like to receive Erasmus+ VETTER project newsletters or further information via email pertaining to the Erasmus+ VETTER project and its results.",
            consent: "I consent to allowing the Erasmus+ VETTER project consortium to send you information via email (including Erasmus+ VETTER project newsletters) pertaining to the Erasmus+ VETTER project and its results.",
        },
        footer: {
            partnership: "Partnership",
            follow_title: "Follow Us",
            follow_subtitle: "Connect with us on social media and get exciting insights and the latest news.",
            disclaimer: "This project has been funded with support from the European Commission. The European Commission's support for the production of this publication does not constitute an endorsement of the contents, which reflect the views only of the authors, and the Commission cannot be held responsible for any use which may be made of the information contained therein.",
        }

    },

    //Turkish
    tr : {
        home: {
            title: "VETTER UYGULAMASINA Hoş Geldiniz",
            description: "Bu Erasmus+ KA2 projesinin amacı, Mesleki Eğitim ve Öğretim ortamındaki üç temel unsurun katılımını geliştirerek Mesleki Eğitim ve Öğretim şirketlerindeki stajların kalitesini artırmaktır: Mesleki eğitim merkezleri, şirketler ve öğrenciler.",
            about_btn: "Proje Hakkında",
            network_btn: "Ağ ve Rozet",
            e_learning_btn: "E-öğrenme Kursu",
            guide_btn: "Metodolojik Rehber",
        },
        about: {
            header: "Proje Hakkında",
            title: "VETTER, Aralık 2021'den Ocak 2024'e kadar sürecek bir Erasmus+ KA2 projesidir.",
            description_p1: "VETTER projesi, MEÖ (Mesleki Eğitim ve Öğretim) öğrencileri tarafından yürütülen stajların değerlendirme ve izleme sürecini iyileştirmeyi amaçlamaktadır ve bu süreç içerisinde kaliteyi artırmayı ve öğrencilerin yaşamının tüm yönlerini dikkate almayı amaçlamaktadır.",
            description_p2: "VETTER projesi, bu süreçleri iyileştirmeyi, öğrencilerin staj döneminin izlenmesini ve değerlendirilmesini ilgili tüm taraflar için daha şeffaf ve faydalı hale getirebilecek yenilikçi yöntemler geliştirmeyi amaçlamaktadır. Bu şekilde, VETTER projesi, mesleki becerilerin dengeli bir karışımını sunan ve tüm ekonomik döngüler, gelişen meslekler, çalışma hayatı ile uyumlu, iş temelli öğrenme fırsatları sunan MEÖ programlarının geliştirilmesini desteklemeye yönelik Erasmus+ programı öncelikleri doğrultusunda yeni yöntemler ve temel yetkinliklerle çalışmayı amaçlamaktadır.",
            description_p3: "Yüksek kaliteli MEÖ için, programların işgücü piyasasının ihtiyaçlarına göre uyarlanmasının yanı sıra sürece dâhil olan Mesleki Eğitim ve Öğretim merkezleri, öğrenciler ve şirketler arasındaki iletişim ve koordinasyonun güçlendirilmesi önemsemektedir. VETTER projesi, mesleki eğitim işe yerleştirme deneyimi, işyerindeki yaşam kalitesini ve işe yerleştirmelerin daha iyi yönetimi ve koordinasyonu için kuruluşlar ve mesleki eğitim merkezleri arasındaki sinerjiyi teşvik etmeyi amaçlamaktadır.",
        },
        e_learning: {
            header: "E-öğrenme Kursu",
            description: "VETTER e-öğrenme kursu, iş yerinde sağlık ve yaşam kalitesinin bütüncül bir şekilde nasıl geliştirileceğine dair 5 modülden oluşan bir uzaktan eğitim kursudur ve hem şirketlere hem de mesleki eğitim merkezlerine somut ihtiyaçları belirleme ve kalitelerini ve koordineli denetimlerini sağlamak için uygulamalarının geliştirilmesinde değişiklikler yapma mekanizmaları sağlar. Bu araç, staja başlamadan önce merkezlerin ve şirketlerin doğru işbirliği metodolojilerini ve iş yerinde yaşam kalitesini sağlamak için kursu tamamlamaları amacıyla tasarlanmıştır.",
            outcome_title: "Kullanıcı nasıl faydalanacak ve ne kazanacak?",
            outcome_description: "Kullanıcı kursu tamamladıktan sonra, kaliteli stajların sağlanmasına yönelik yöntem ve uygulamalar, işe yerleştirme sürecinin tamamını kapsayan kaynaklar, işe yerleştirmenin başından sonuna kadar kalite yönergelerinin ve direktiflerinin nasıl oluşturulacağı ve tabii ki kaliteli stajların nasıl sağlanacağına ilişkin uygulamalar gibi bir stajın tüm yönleri hakkında önemli bilgi ve anlayış kazanmış olacaktır.",
            get_course_now: "Kursa şimdi katılın",
            beneficiaries_title: "Yararlanıcılar",
            beneficiary_1: "Staj Eğitmenleri",
            beneficiary_2: "Mentorlar",
            beneficiary_3: "Kariyer Danışmanları",
            beneficiary_4: "Mesleki Eğitim ve Öğretim ( MEÖ ) Okulları",
            beneficiary_5: "Şirketler",
            beneficiary_6: "İşe yerleştirmelerde yer alan işverenler ve stajyerler",
        },
        methodological_guide: {
            header: "Metodolojik Rehber",
            description_p1: "Ortaklık, iş yerinde yaşam kalitesini, sağlığı, stajların koordinasyonunu ve takibini iyileştirmek için bir dizi kılavuz ve tavsiyeyle birlikte şirketlere ve Mesleki Eğitim ve Öğretim merkezlerine yönelik bir rehber geliştirdi.",
            description_p2: "Bu, stajların değerini en üst düzeye çıkaran uygun ve denetleyici bir ortamda gerçekleşmesini sağlayacaktır.",
            description_p3: "Metodolojik rehber, temel kalite yönergeleri sağlayarak esas olarak yerleştirmelerin koordineli bir şekilde uygulanmasına yönelik olacak ve hem şirketlerin hem de Mesleki Eğitim ve Öğretim merkezlerinin staj dönemini daha organize bir şekilde yönetmelerine olanak tanıyarak gelecekte hareketlilik projeleri için önemli bir araç haline gelebilecektir.",
            coming_soon: "Kılavuzu indirin",
        },
        network: {
            header: "Ağ & Rozet",
            description_p1: "Bir şirketten veya mesleki eğitim ve öğretim ( MEÖ) kurumundan kalifiye bir profesyonel olarak, artık uluslararası VETTER Ağımıza kaydolma fırsatına sahipsiniz.",
            description_p2: "Uluslararası VETTER Ağı, mesleki becerilerin dengeli bir karışımını sunan ve tüm ekonomik döngülere, gelişen işlere, çalışma yöntemlerine ve temel yeterliliklere iyi bir şekilde uyarlanmış iş temelli öğrenme fırsatları yaratan mesleki eğitim programlarının geliştirilmesini desteklemeye yönelik Erasmus + önceliğine bağlı olarak Avrupa (yani Almanya, İtalya, Yunanistan, Güney Kıbrıs ) ve Türkiye'de - ve ötesinde - benzer düşünen bireyleri ve kuruluşları bir araya getirmektedir.",
            description_p3: "VETTER Ağına katılarak, mesleki eğitim ve öğretim ( MEÖ) yerleştirmelerinin daha iyi deneyimlenmesini, işyerinde yaşam kalitesini ve işe yerleştirmelerin daha iyi yönetimi ve koordinasyonu için kuruluşlar ve MEÖ merkezleri arasındaki sinerjiyi teşvik etmek amacıyla Erasmus+ VETTER proje değerlerine uyum sağlamayı taahhüt ediyorsunuz. Bir ağ üyesi olarak, projenin hedeflerine bağlı kalacağınızı ve fikri ürünlerini (ücretsiz, açık kaynaklı, Avrupa tarafından finanse edilen VETTER e-Öğrenim kursu, mobil uygulama ve dijital metodolojik rehber kitap) kullanacağınızı taahhüt etmiş bulunuyorsunuz.",
            join_form_title: "VETTER Ağına Katılın",
            fullname: "Ad Soyad",
            country: "Ülke",
            organization: "Kurum (isteğe bağlı)",
            email: "E-posta Adresi",
            apply_now: "Şimdi Başvur",
            email_sent: "Talep e-postası gönderildi!",
            email_not_valid: "Geçerli bir e-posta değil.",
            required_field: "Bu alan gereklidir.",
            newsletter: "Erasmus+ VETTER projesi bültenlerini veya Erasmus+ VETTER projesi ve sonuçlarına ilişkin e-posta yoluyla daha fazla bilgi almak istiyorum.",
            consent: "Erasmus+ VETTER proje konsorsiyumunun size Erasmus+ VETTER projesi ve sonuçlarıyla ilgili e-posta yoluyla bilgi (Erasmus+ VETTER proje haber bültenleri dahil) göndermesine izin veriyorum.",

        },
        footer: {
            partnership: "Ortaklık",
            follow_title: "Bizi takip edin",
            follow_subtitle: "Bizimle sosyal medyada bağlantı kurun ve heyecan verici bilgiler ve en son haberleri alın.",
            disclaimer: "Bu proje Avrupa Komisyonu'nun desteği ile finanse edilmektedir. Avrupa Komisyonu'nun bu yayının hazırlanmasına verdiği destek, sadece yazarların görüşlerini yansıtan içeriğin onaylandığı anlamına gelmez ve Komisyon burada yer alan bilgilerin herhangi bir şekilde kullanılmasından sorumlu tutulamaz.",
        }

    },

    //Italian
    it : {
        home: {
            title: "Benvenuto sull'APP VETTER",
            description: "L'obiettivo di questo progetto Erasmus+ KA2 è quello di migliorare la qualità dei tirocini nelle aziende di formazione professionale favorendo il coinvolgimento e la partecipazione dei tre attori chiave nell’ambito della formazione professionale: Centri di formazione professionale, aziende e studenti.",
            about_btn: "Sul progetto",
            network_btn: "Network e badge",
            e_learning_btn: "Corso e-learning",
            guide_btn: "Guida metodologica",
        },
        about: {
            header: "Il Progetto",
            title: "VETTER è un progetto Erasmus+ KA2, iniziato a dicembre 2021 e che si concluderà a gennaio 2024.",
            description_p1: "Il progetto VETTER ha l'obiettivo di migliorare il processo di valutazione e monitoraggio dei tirocini svolti dagli studenti IFP, dal momento che, spesso, non è qualitativamente adeguato e non tiene conto di diverse dimensioni della vita degli studenti.",
            description_p2: "Il progetto VETTER ha dunque lo scopo di migliorare questi processi, fornendo nuove metodologie e metodi innovativi che possano rendere il monitoraggio e la valutazione del periodo di tirocinio degli studenti più trasparente e utile per tutte le parti coinvolte. In questo modo, il progetto VETTER intende operare in linea con la priorità di Erasmus+ di sostenere lo sviluppo di programmi di IFP che offrano un mix equilibrato di competenze professionali e creino opportunità di apprendimento basate sul lavoro ben allineate a tutti i cicli economici, all'evoluzione dei posti di lavoro, ai metodi di lavoro e alle competenze chiave.",
            description_p3: "Per offrire una formazione IFP di alta qualità, è necessario adattare i programmi alle esigenze del mercato del lavoro e rafforzare la comunicazione e il coordinamento tra gli attori coinvolti nel processo: Centri di formazione professionale, studenti e aziende. Questo progetto mira a promuovere l'esperienza dei tirocini IFP, la qualità della vita sul posto di lavoro e le sinergie tra organizzazioni e centri IFP per una migliore gestione e coordinamento dei tirocini.",
        },
        e_learning: {
            header: "Corso E-Learning",
            description: "Il corso e-learning VETTER è un corso MOOC con 5 moduli su come migliorare la salute e la qualità della vita sul lavoro in modo olistico, oltre a fornire meccanismi sia per le aziende che per i centri di formazione professionale per identificare esigenze concrete e attuare cambiamenti nello sviluppo delle loro pratiche per garantirne la qualità e la supervisione coordinata. Questo strumento è stato progettato in modo che, prima di iniziare il tirocinio, i centri e le aziende completino questo corso per garantire le giuste metodologie di cooperazione e la qualità della vita sul lavoro.",
            outcome_title: "Quali benefici trarrà l'utente, cosa otterrà?",
            outcome_description: "Al termine del corso, l'utente avrà acquisito una conoscenza e una comprensione di tutti gli aspetti di uno stage, come i metodi e le pratiche per garantire stage di qualità, le risorse che coprono l'intero processo di inserimento lavorativo, come stabilire linee guida e direttive di qualità dall'inizio alla fine dello stage e, naturalmente, le pratiche su come garantire stage di qualità in generale.",
            get_course_now: "Accedi al corso ora",
            beneficiaries_title: "Beneficiari",
            beneficiary_1: "Tutor del tirocinio",
            beneficiary_2: "Mentori",
            beneficiary_3: "Consulenti di carriera",
            beneficiary_4: "Scuole IFP",
            beneficiary_5: "Aziende",
            beneficiary_6: "Datori di lavoro coinvolti nell'inserimento lavorativo e nei tirocini/stage",
        },
        methodological_guide: {
            header: "Guida metodologica",
            description_p1: "Il partenariato ha sviluppato una guida rivolta alle aziende e ai centri di formazione professionale con una serie di linee guida e raccomandazioni per migliorare la qualità della vita sul lavoro, la salute, il coordinamento dei tirocini e il loro follow-up.",
            description_p2: "In questo modo si garantirà che essi si svolgano in un ambiente adeguato e controllato che ne massimizzi il valore.",
            description_p3: "La guida metodologica sarà orientata principalmente all'attuazione coordinata dei tirocini, fornendo linee guida di base sulla qualità e potrebbe diventare uno strumento importante per i progetti di mobilità in futuro, consentendo sia alle aziende che ai centri di formazione professionale di gestire il periodo di tirocinio in modo più organizzato.",
            coming_soon: "Scarica la guida",
        },
        network: {
            header: "Network (rete) e badge",
            description_p1: "In qualità di professionista qualificato di un'azienda o di un istituto di istruzione e formazione professionale, avete ora l'opportunità di registrarvi alla nostra Rete VETTER internazionale.",
            description_p2: "La Rete internazionale VETTER riunisce persone e organizzazioni simili in tutta Europa (Germania, Italia, Grecia, Cipro) e in Turchia (e non solo), impegnate nella priorità di Erasmus+ di sostenere lo sviluppo di programmi di istruzione e formazione professionale che offrano un mix equilibrato di competenze professionali e creino opportunità di apprendimento basate sul lavoro ben allineate a tutti i cicli economici, all'evoluzione dei posti di lavoro, ai metodi di lavoro e alle competenze chiave.",
            description_p3: "Aderendo alla Rete (al Network) VETTER, vi impegnate ad allinearvi ai valori del progetto Erasmus+ VETTER per promuovere il miglioramento dell'esperienza dei tirocini di istruzione e formazione professionale (VET), la qualità della vita sul posto di lavoro e le sinergie tra organizzazioni e centri VET per una migliore gestione e coordinamento dei tirocini. In qualità di membro della rete, vi impegnate ad aderire agli obiettivi del progetto e a utilizzare i suoi prodotti intellettuali - il corso e-learning gratuito, open-source e finanziato dall'Europa VETTER, l'applicazione mobile e la guida metodologica digitale.",
            join_form_title: "Unisciti al network VETTER",
            fullname: "Nome completo",
            country: "Paese",
            organization: "Organizzazione (opzionale)",
            email: "Indirizzo email",
            apply_now: "Candidati ora",
            email_sent: "Richiesta email inviata!",
            email_not_valid: "Non è un'e-mail valida.",
            required_field: "Questo campo è obbligatorio.",
            newsletter: "Desidero ricevere le newsletter del progetto Erasmus+ VETTER o ulteriori informazioni via e-mail relative al progetto Erasmus+ VETTER e ai suoi risultati.",
            consent: "Acconsento a consentire al consorzio del progetto Erasmus+ VETTER di inviarti informazioni via email (comprese le newsletter del progetto Erasmus+ VETTER) relative al progetto Erasmus+ VETTER e ai suoi risultati.",

        },
        footer: {
            partnership: "Partenariato",
            follow_title: "Seguici",
            follow_subtitle: "Connettetevi con noi sui social media per ricevere approfondimenti interessanti e le ultime notizie.",
            disclaimer: "Questo progetto è stato finanziato con il sostegno della Commissione europea. Il sostegno della Commissione europea alla realizzazione di questa pubblicazione non costituisce un'approvazione dei contenuti, che riflettono esclusivamente il punto di vista degli autori, e la Commissione non può essere ritenuta responsabile per l'uso che può essere fatto delle informazioni in essa contenute.",
        }

    },

    //Greek
    el : {
        home: {
            title: "Καλώς ήρθατε στην εφαρμογή VETTER",
            description: "Ο στόχος αυτού του έργου Erasmus+ KA2 είναι να βελτιώσει την ποιότητα της πρακτικής άσκησης σε επιχειρήσεις ΕΕΚ βελτιώνοντας τη συμμετοχή των τριών βασικών φορέων στο περιβάλλον της επαγγελματικής κατάρτισης: Κέντρα ΕΕΚ, επιχειρήσεις & σπουδαστές.",
            about_btn: "Σχετικά με το έργο",
            network_btn: "Δίκτυο & Σήμα",
            e_learning_btn: "Μάθημα E-learning",
            guide_btn: "Μεθοδολογικός οδηγός",
        },
        about: {
            header: "Σχετικά με το έργο",
            title: "Το VETTER είναι ένα έργο Erasmus+ KA2 που θα διαρκέσει από τον Δεκέμβριο του 2021 έως τον Ιανουάριο του 2024.",
            description_p1: "Το έργο VETTER αποσκοπεί στη βελτίωση της διαδικασίας αξιολόγησης και παρακολούθησης της πρακτικής άσκησης που πραγματοποιούν οι σπουδαστές της επαγγελματικής εκπαίδευσης και κατάρτισης, καθώς η διαδικασία αυτή μερικές φορές δεν είναι ποιοτική και δεν λαμβάνει υπόψη διάφορες διαστάσεις της ζωής των σπουδαστών.",
            description_p2: "Το VETTER στοχεύει στη βελτίωση αυτών των διαδικασιών, παρέχοντας νέες μεθοδολογίες και καινοτόμες μεθόδους που μπορούν να καταστήσουν την παρακολούθηση και την αξιολόγηση της περιόδου πρακτικής άσκησης των σπουδαστών πιο διαφανή και χρήσιμη για όλα τα εμπλεκόμενα μέρη. Με αυτόν τον τρόπο, το έργο στοχεύει στην υποστήριξη της ανάπτυξης προγραμμάτων επαγγελματικής εκπαίδευσης και κατάρτισης που προσφέρουν ένα ισορροπημένο μείγμα επαγγελματικών δεξιοτήτων και δημιουργούν ευκαιρίες μάθησης με βάση την εργασία, σε συνάρτηση με όλους τους οικονομικούς κύκλους, τις εξελισσόμενες θέσεις εργασίας, τις μεθόδους εργασίας και τις βασικές ικανότητες.",
            description_p3: "Για την παροχή υψηλής ποιότητας κατάρτισης στην ΕΕΚ, είναι απαραίτητο να προσαρμοστούν τα προγράμματα στις ανάγκες της αγοράς εργασίας, καθώς και να ενισχυθεί η επικοινωνία και ο συντονισμός μεταξύ των παραγόντων που εμπλέκονται στη διαδικασία: Κέντρα επαγγελματικής εκπαίδευσης και κατάρτισης, σπουδαστές και επιχειρήσεις. Το VETTER στοχεύει στην προώθηση της εμπειρίας της πρακτικής άσκησης στην ΕΕΚ, της ποιότητας της ζωής στην εργασία και των συνεργειών μεταξύ οργανισμών και κέντρων ΕΕΚ για την καλύτερη διαχείριση και τον συντονισμό της πρακτικής άσκησης.",
        },
        e_learning: {
            header: "Μάθημα E-learning",
            description: "Το μάθημα ηλεκτρονικής μάθησης VETTER είναι ένα μάθημα MOOC με 5 ενότητες για τον τρόπο βελτίωσης της υγείας και της ποιότητας ζωής στην εργασία με ολιστικό τρόπο, καθώς και για την παροχή μηχανισμών τόσο σε επιχειρήσεις όσο και στα κέντρα επαγγελματικής κατάρτισης για τον εντοπισμό συγκεκριμένων αναγκών και την εφαρμογή αλλαγών στην ανάπτυξη των πρακτικών τους, ώστε να διασφαλίζεται η ποιότητα και η συντονισμένη εποπτεία τους. Το εργαλείο αυτό έχει σχεδιαστεί έτσι ώστε, πριν από την έναρξη της πρακτικής άσκησης, τα κέντρα και οι επιχειρήσεις να ολοκληρώνουν αυτό το μάθημα για να διασφαλίσουν τις σωστές μεθοδολογίες συνεργασίας και την ποιότητα ζωής στην εργασία.",
            outcome_title: "Πώς θα ωφεληθεί ο χρήστης και τι θα κερδίσει;",
            outcome_description: "Αφού ο χρήστης ολοκληρώσει το μάθημα, θα έχει αποκτήσει σημαντικές γνώσεις και κατανόηση όλων των πτυχών μιας πρακτικής άσκησης - όπως μέθοδοι και πρακτικές για τη διασφάλιση ποιοτικής πρακτικής άσκησης, πηγές που καλύπτουν ολόκληρη τη διαδικασία πρακτικής άσκησης, τον τρόπο θέσπισης κατευθυντήριων γραμμών και οδηγιών ποιότητας από την αρχή έως το τέλος της πρακτικής άσκησης και, φυσικά, πρακτικές για τη διασφάλιση ποιοτικής πρακτικής άσκησης συνολικά.",
            get_course_now: "Αποκτήστε το μάθημα τώρα",
            beneficiaries_title: "Δικαιούχοι",
            beneficiary_1: "Καθηγητές πρακτικής άσκησης",
            beneficiary_2: "Μέντορες",
            beneficiary_3: "Σύμβουλοι καριέρας",
            beneficiary_4: "Σχολές Επαγγελματικής Εκπαίδευσης και Κατάρτισης (ΕΕΚ)",
            beneficiary_5: "Εταιρείες",
            beneficiary_6: "Εργοδότες που εμπλέκονται σε πρακτική άσκηση και ασκούμενους/ ασκούμενες.",
        },
        methodological_guide: {
            header: "Μεθοδολογικός οδηγός",
            description_p1: "Το εταιρικό σχήμα ανέπτυξε έναν οδηγό που απευθύνεται σε επιχειρήσεις και κέντρα επαγγελματικής εκπαίδευσης και κατάρτισης με μια σειρά κατευθυντήριων γραμμών και συστάσεων για τη βελτίωση της ποιότητας ζωής στην εργασία, της υγείας, του συντονισμού της πρακτικής άσκησης και της παρακολούθησής της.",
            description_p2: "Με τον τρόπο αυτό θα διασφαλιστεί ότι οι πρακτικές ασκήσεις πραγματοποιούνται σε κατάλληλο, εποπτικό περιβάλλον που μεγιστοποιεί την αξία τους.",
            description_p3: "Ο μεθοδολογικός οδηγός θα προσανατολίζεται κυρίως στη συντονισμένη υλοποίηση της πρακτικής άσκησης παρέχοντας βασικές κατευθυντήριες γραμμές ποιότητας και θα μπορούσε να αποτελέσει ένα σημαντικό εργαλείο για τα σχέδια κινητικότητας στο μέλλον, επιτρέποντας τόσο στις επιχειρήσεις όσο και στα κέντρα επαγγελματικής εκπαίδευσης και κατάρτισης να διαχειρίζονται την περίοδο πρακτικής άσκησης με πιο οργανωμένο τρόπο.",
            coming_soon: "Κατεβάστε τον οδηγό",
        },
        network: {
            header: "Δίκτυο & Σήμα",
            description_p1: "Ως εξειδικευμένος επαγγελματίας είτε από εταιρεία είτε από ίδρυμα επαγγελματικής εκπαίδευσης και κατάρτισης (ΕΕΚ), έχετε τώρα την ευκαιρία να εγγραφείτε στο διεθνές μας δίκτυο VETTER.",
            description_p2: "Το διεθνές Δίκτυο VETTER συγκεντρώνει όμοιους οργανισμούς στην Ευρώπη (π.χ. Γερμανία, Ιταλία, Ελλάδα, Κύπρος) και την Τουρκία - και όχι μόνο - που δεσμεύονται για την προτεραιότητα του Erasmus+ να στηρίξουν την ανάπτυξη προγραμμάτων ΕΕΚ που προσφέρουν ένα ισορροπημένο μείγμα επαγγελματικών δεξιοτήτων και δημιουργούν ευκαιρίες μάθησης με βάση την εργασία σε συνάφεια με όλους τους οικονομικούς κύκλους, τις εξελισσόμενες θέσεις εργασίας και τις μεθόδους εργασίας και τις βασικές ικανότητες.",
            description_p3: "Με την ένταξή σας στο δίκτυο VETTER, δεσμεύεστε να ευθυγραμμιστείτε με τις αξίες του έργου VETTER του Erasmus+ για την προώθηση της βελτιωμένης εμπειρίας της πρακτικής άσκησης στην επαγγελματική εκπαίδευση και κατάρτιση (ΕΕΚ), της ποιότητας ζωής στην εργασία και των συνεργειών μεταξύ οργανισμών και κέντρων ΕΕΚ για την καλύτερη διαχείριση και τον καλύτερο συντονισμό της πρακτικής άσκησης. Ως μέλος του δικτύου, δεσμεύεστε να τηρείτε τους στόχους του έργου και να χρησιμοποιείτε τα πνευματικά του προϊόντα - το δωρεάν, ανοικτού κώδικα, χρηματοδοτούμενο από την Ευρωπαϊκή Ένωση μάθημα ηλεκτρονικής μάθησης VETTER, την εφαρμογή για κινητά και τον ψηφιακό οδηγό μεθοδολογίας.",
            join_form_title: "Εγγραφείτε στο δίκτυο VETTER",
            fullname: "Ονοματεπώνυμο",
            country: "Χώρα",
            organization: "Οργανισμός (προαιρετικά)",
            email: "E-mail",
            apply_now: "Κάντε αίτηση τώρα",
            email_sent: "Το αίτημα στάλθηκε!",
            email_not_valid: "Μη έγκυρο email.",
            required_field: "Αυτό το πεδίο είναι υποχρεωτικό.",
            newsletter: "Θα ήθελα να λαμβάνω ενημερωτικά δελτία του έργου Erasmus+ VETTER ή περισσότερες πληροφορίες μέσω email σχετικά με το έργο Erasmus+ VETTER και τα αποτελέσματά του.",
            consent: "Συμφωνώ να επιτρέψω στην κοινοπραξία του έργου Erasmus+ VETTER να σας στέλνει πληροφορίες μέσω email (συμπεριλαμβανομένων των ενημερωτικών δελτίων του έργου Erasmus+ VETTER) σχετικά με το έργο Erasmus+ VETTER και τα αποτελέσματά του.",

        },
        footer: {
            partnership: "Εταιρικό Σχήμα",
            follow_title: "Ακολουθήστε μας",
            follow_subtitle: "Συνδεθείτε μαζί μας στα μέσα κοινωνικής δικτύωσης για πληροφορίες και τελευταία νέα.",
            disclaimer: "Η υποστήριξη της Ευρωπαϊκής Επιτροπής στην παραγωγή της παρούσας έκδοσης δεν συνιστά αποδοχή του περιεχομένου, το οποίο αντικατοπτρίζει αποκλειστικά τις απόψεις των συντακτών, και η Επιτροπή δεν μπορεί να αναλάβει την ευθύνη για οποιαδήποτε χρήση των πληροφοριών που περιέχονται σε αυτήν.",
        }

    },

    //German
    de :{
        home: {
            title: "Willkommen bei der VETTER APP",
            description: "Das Ziel dieses Erasmus+ KA2-Projekts ist es, die Qualität von Praktika in berufsbildenden Unternehmen zu verbessern, indem die Einbeziehung und Beteiligung der drei Hauptakteure im Umfeld der Berufsbildung verbessert wird: Berufsbildungszentren, Unternehmen und Studierende.",
            about_btn: "Über das Projekt",
            network_btn: "Netzwerk & Abzeichen",
            e_learning_btn: "E-learning Kurs",
            guide_btn: "Methodischer Leitfaden",
        },
        about: {
            header: "Über das Projekt",
            title: "VETTER ist ein Erasmus+ KA2 Projekt, das von Dezember 2021 bis Januar 2024 läuft.",
            description_p1: "Das Projekt VETTER zielt darauf ab, den Evaluierungs- und Überwachungsprozess von Praktika zu verbessern, die von Studierenden der beruflichen Bildung absolviert werden, da es diesem Prozess manchmal an Qualität mangelt und verschiedene Dimensionen des Lebens der Studierenden nicht berücksichtigt werden.",
            description_p2: "Das VETTER-Projekt zielt darauf ab, diese Prozesse zu verbessern, indem es neue Methodologien und innovative Methoden bereitstellt, die die Überwachung und Bewertung der Praktikumszeit von Studenten transparenter und für alle Beteiligten nützlicher machen können. Auf diese Weise will das VETTER-Projekt im Sinne der Erasmus+-Priorität die Entwicklung von Berufsbildungsprogrammen unterstützen, die eine ausgewogene Mischung beruflicher Fähigkeiten bieten und arbeitsbezogene Lernmöglichkeiten schaffen, die auf alle Wirtschaftszyklen, sich entwickelnde Arbeitsplätze, Arbeitsmethoden und Schlüsselkompetenzen abgestimmt sind.",
            description_p3: "Um eine qualitativ hochwertige Berufsausbildung zu gewährleisten, müssen die Programme an die Bedürfnisse des Arbeitsmarktes angepasst und die Kommunikation und Koordination zwischen den am Prozess beteiligten Akteuren gestärkt werden: Berufsbildungszentren, Auszubildende und Unternehmen. Dieses Projekt zielt darauf ab, die Erfahrungen mit Berufspraktika, die Qualität des Arbeitslebens und Synergien zwischen Organisationen und Berufsbildungszentren zu fördern, um eine bessere Verwaltung und Koordinierung von Praktika zu erreichen.",
        },
        e_learning: {
            header: "E-learning Kurs",
            description: "Der E-Learning-Kurs VETTER ist ein MOOC-Kurs mit 5 Modulen zur ganzheitlichen Verbesserung von Gesundheit und Lebensqualität am Arbeitsplatz. Er bietet sowohl Unternehmen als auch Berufsbildungszentren Mechanismen zur Ermittlung konkreter Bedürfnisse und zur Umsetzung von Änderungen bei der Entwicklung ihrer Praktiken, um deren Qualität und koordinierte Überwachung zu gewährleisten. Dieses Instrument ist so konzipiert, dass die Zentren und Unternehmen vor Beginn des Praktikums diesen Kurs absolvieren, um die richtigen Methoden der Zusammenarbeit und die Qualität des Lebens am Arbeitsplatz zu gewährleisten.",
            outcome_title: "Welchen Nutzen hat der Nutzer und was wird er/sie gewinnen?",
            outcome_description: "Nach Beendigung des Kurses wird der Nutzer wichtige Kenntnisse und ein Verständnis für alle Aspekte eines Praktikums erlangt haben - wie z. B. Methoden und Praktiken zur Sicherstellung qualitativ hochwertiger Praktika, Ressourcen, die den gesamten Praktikumsprozess abdecken, wie man Qualitätsrichtlinien und -anweisungen vom Beginn bis zum Ende des Praktikums aufstellt, und natürlich Praktiken zur Sicherstellung qualitativ hochwertiger Praktika im Ganzen.",
            get_course_now: "Holen Sie sich den Kurs jetzt",
            beneficiaries_title: "Nutznießer",
            beneficiary_1: "Praktikumsbetreuer",
            beneficiary_2: "Mentoren",
            beneficiary_3: "Berufsberater",
            beneficiary_4: "Schulen für berufliche Bildung und Ausbildung (VET)",
            beneficiary_5: "Unternehmen",
            beneficiary_6: "Arbeitgeber, die an Praktika und Auszubildenden/Praktikanten beteiligt sind.",
        },
        methodological_guide: {
            header: "Methodischer Leitfaden",
            description_p1: "Die Partnerschaft hat einen Leitfaden entwickelt, der sich an Unternehmen und Berufsbildungszentren richtet und eine Reihe von Leitlinien und Empfehlungen zur Verbesserung der Qualität des Arbeitslebens, der Gesundheit, der Koordination von Praktika und ihrer Nachbereitung enthält.",
            description_p2: "Damit soll sichergestellt werden, dass die Praktika in einem geeigneten, betreuten Umfeld stattfinden, das ihren Wert maximiert.",
            description_p3: "Der methodische Leitfaden wird hauptsächlich auf die koordinierte Durchführung von Praktika ausgerichtet sein, indem er grundlegende Qualitätsrichtlinien bereitstellt, und könnte in Zukunft ein wichtiges Instrument für Mobilitätsprojekte werden, das es sowohl Unternehmen als auch Berufsbildungszentren ermöglicht, die Praktikumszeit besser zu organisieren.",
            coming_soon: "Anleitung herunterladen",
        },
        network: {
            header: "Netzwerk & Abzeichen",
            description_p1: "Als qualifizierte Fachkraft aus einem Unternehmen oder einer Berufsbildungseinrichtung haben Sie jetzt die Möglichkeit, sich für unser internationales VETTER-Netzwerk zu registrieren.",
            description_p2: "Das internationale VETTER-Netzwerk bringt gleichgesinnte Personen und Organisationen aus ganz Europa (z.B. Deutschland, Italien, Griechenland, Zypern) und der Türkei - und darüber hinaus - zusammen, die sich der Erasmus+ Priorität verschrieben haben, die Entwicklung von Berufsbildungsprogrammen zu unterstützen, die eine ausgewogene Mischung von beruflichen Fähigkeiten anbieten und arbeitsbezogene Lernmöglichkeiten schaffen, die gut auf alle Wirtschaftszyklen, sich entwickelnde Arbeitsplätze, Arbeitsmethoden und Schlüsselkompetenzen abgestimmt sind.",
            description_p3: "Mit dem Beitritt zum VETTER-Netzwerk verpflichten Sie sich, sich an den Werten des Erasmus+ VETTER-Projekts zu orientieren, um die Erfahrungen mit Praktika in der Berufsbildung und die Lebensqualität am Arbeitsplatz zu verbessern und Synergien zwischen Organisationen und Berufsbildungszentren für eine bessere Verwaltung und Koordination von Praktika zu fördern. Als Mitglied des Netzwerks verpflichten Sie sich, die Ziele des Projekts einzuhalten und seine geistigen Produkte zu nutzen - den kostenlosen, quelloffenen und von der EU finanzierten e-Learning-Kurs VETTER, die mobile App und den digitalen methodischen Leitfaden.",
            join_form_title: "Werden Sie Mitglied im VETTER-Netzwerk",
            fullname: "Vollständiger Name",
            country: "Land",
            organization: "Organisation (optional)",
            email: "E-Mail Adresse",
            apply_now: "Jetzt bewerben",
            email_sent: "Anfrage-E-Mail gesendet!",
            email_not_valid: "Keine gültige E-Mail.",
            required_field: "Dieses Feld ist erforderlich.",
            newsletter: "Ich möchte Newsletter des Erasmus+ VETTER-Projekts oder weitere Informationen per E-Mail zum Erasmus+ VETTER-Projekt und seinen Ergebnissen erhalten.",
            consent: "Ich bin damit einverstanden, dass das Erasmus+ VETTER-Projektkonsortium Ihnen per E-Mail Informationen (einschließlich Erasmus+ VETTER-Projektnewsletter) zum Erasmus+ VETTER-Projekt und seinen Ergebnissen zusendet.",
        },
        footer: {
            partnership: "Partnerschaft",
            follow_title: "Folgen Sie uns",
            follow_subtitle: "Verbinden Sie sich mit uns in den sozialen Medien und erhalten Sie spannende Einblicke und die neuesten Nachrichten.",
            disclaimer: "Dieses Projekt wurde mit Unterstützung der Europäischen Kommission finanziert. Die Unterstützung der Europäischen Kommission für die Erstellung dieser Publikation stellt keine Billigung des Inhalts dar, der ausschließlich die Meinung der Autoren wiedergibt, und die Kommission kann nicht für die Verwendung der darin enthaltenen Informationen verantwortlich gemacht werden.",
        }
    }

}
export { translations };